### ISSUE TITLE
Input check for the "Entry" search field

### ISSUE THREAD

**Issue by Carbenium** [Helias/Keira2#2]
baf27a72cb18614f626bce88122408f3ffeb9c9f
The above mentioned field accepts alphanumeric characters without complaining, wich doesn't really make sense. Instead performing the search an error message should be displayed.

**Comment by Helias** [comment]
Fixed https://github.com/Helias/Keira2/commit/5d1be0f42bdb01bb8c1bdc97d05ff9cb8a75db93
Thank you for the report ;).
