### ISSUE TITLE
Suggestion? 

### ISSUE THREAD

**Issue by prestonjamesparsons** [Helias/Keira2#20]
Hi, Would there any option for connection to own database as if u pick some creature and change something as will it import automatically rather import it manually ?

**Comment by tkrokli** [comment]
I don't know (Helias & ShinDarth knows), but I would like to suggest 2 possible answers (50/50):

A) Not yet implemented, but that functionality is a planned future feature.
-- or --
B) No, the methods are not considered safe enough for direct database editing.

**Comment by ShinDarth** [comment]
Yes @tkrokli said both the points. We plan to implement that feature, and without API authentication it is not safe to edit the database directly. So we have to implement API autentication first.

See https://github.com/Helias/Keira2/issues/15
