### ISSUE TITLE
Misleading visual values in the `event_flags` pop-up list

### ISSUE THREAD

**Issue by tkrokli** [Helias/Keira2#25]
When comparing the "Flags" values in Keira2 (online test version, 3.3.5) with TC wiki, values in the pop-up list from "Flags" seem incorrect. Copy-paste from Keira2 pop-up from 'Flags' :
```
0 NOT_REPEATABLE
1 DIFFICULTY_0
2 DIFFICULTY_1
3 DIFFICULTY_2
4 DIFFICULTY_3
5 RESERVED_5 (not used)
6 RESERVED_6 (not used)
7 DEBUG_ONLY
```
Values in `event_flags` table from TC wiki:
https://trinitycore.atlassian.net/wiki/display/tc/smart_scripts#smart_scripts-event_flags

| Name        | Flag           | Hex  | Comment |
| ------------- | -------------:| -----:| ------------- |
| SMART_EVENT_FLAG_NOT_REPEATABLE |   1 |  0x01 | Event can not repeat                           |
| SMART_EVENT_FLAG_DIFFICULTY_0   |   2 |  0x02 | Event only occurs in normal dungeon            |
| SMART_EVENT_FLAG_DIFFICULTY_1   |   4 |  0x04 | Event only occurs in heroic dungeon            |
| SMART_EVENT_FLAG_DIFFICULTY_2   |   8 |  0x08 | Event only occurs in normal raid               |
| SMART_EVENT_FLAG_DIFFICULTY_3   |  16 |  0x10 | Event only occurs in heroic raid               |
| SMART_EVENT_FLAG_DEBUG_ONLY     | 128 |  0x80 | Event only occurs in debug build               |
| SMART_EVENT_FLAG_DONT_RESET     | 256 | 0x100 | Event will not reset in SmartScript::OnReset() |

I don't know how Keira2 applies the flags or if the wiki page is outdated or incorrect, but I find the Keira2 example table somewhat confusing when it comes to using `event_flags` = 0, which should mean "Flag not set, empty value" to the user. The visual value selection in the table will make a user like me think that 0 means 'Not repeatable', which actually is 1 in the script and in the wiki page.

If I may suggest what the visual pop-up could look like, here is an example list:
```
  0 FLAG_NOT_SET (placeholder/empty value)
  1 NOT_REPEATABLE (Event can not repeat)
  2 DIFFICULTY_0 (Normal dungeon)
  4 DIFFICULTY_1 (Heroic dungeon)
  8 DIFFICULTY_2 (Normal raid)
 16 DIFFICULTY_3 (Heroic raid)
 32 RESERVED_5 (not used)
 64 RESERVED_6 (not used)
128 DEBUG_ONLY (only used in debug build)
256 DONT_RESET (Event will not reset)
```

I hope this explains my issue well enough. Feel free to ask if you need more information. :)

**Comment by Helias** [comment]
Thanks @tkrokli for the report but the visual values of flags are all "incorrect". What means? The real values of the flag values are 2^value, example

```0 NOT_REPEATABLE
1 DIFFICULTY_0
2 DIFFICULTY_1
3 DIFFICULTY_2
4 DIFFICULTY_3
5 RESERVED_5 (not used)
6 RESERVED_6 (not used)
7 DEBUG_ONLY```

real values:

```2^0 NOT_REPEATABLE
2^1 DIFFICULTY_0
2^2 DIFFICULTY_1
2^3 DIFFICULTY_2
2^4 DIFFICULTY_3
2^5 RESERVED_5 (not used)
2^6 RESERVED_6 (not used)
2^7 DEBUG_ONLY```

All the flag values work in this way.

Anyway, I'll add the "DONT RESET" value, probably I'll add in future some help description in the editor also about the flag value system.

**Comment by tkrokli** [comment]
OK, I did not specify clearly enough that I counted on Keira2 inserting the correct values.

My only point is that for users thinking in decimal notation, it becomes a logical error for them to read the first setting as `0 (NOT_REPEATABLE)` in the pop-up window, because the visual value (in decimal) seen in the script is `1 (NOT_REPEATABLE)` . Then again, I did not remember that most coders think in hex and exponents like this: 2<sup>0</sup>, 2<sup>1</sup>, 2<sup>2</sup>, 2<sup>3</sup>, 2<sup>4</sup>, 2<sup>5</sup>, 2<sup>6</sup>, 2<sup>7</sup>

I suppose that **most users** who use the `event_flags` value knows what it does - and those who don't know, will not use it. From that point of view, it is purely cosmetic. True, for most users it will be meaningless to add the 0 FLAG_NOT_SET (placeholder/empty value) as an option to tick off in one of the boxes, because if we don't tick any of the options, zero is used and nothing changes.
Sorry for the confusioin. I am possibly one of the few lowbie users who don't think in code all the time. ;-)
