### ISSUE TITLE
Version switching (3.3.5/6.x) on the dev server

### ISSUE THREAD

**Issue by tkrokli** [Helias/Keira2#26]
http://keira2.altervista.org/Keira2-dev/#/ <= very little indication of DB change in the GUI

When pressing the [Version 3.3.35] button and selecting 6.x, only 1 blue button is removed (in addition to the action button name change). The rest of the page info still shows that you are using 3.3.5.

**Comment by ShinDarth** [comment]
yeah I fear this is not a bug: I didn't configured 6.x database for that instance yet because of my slow connection here. But thanks a lot anyway for your report.
