### ISSUE TITLE
Make even for 2.4.3

### ISSUE THREAD

**Issue by cyberpro98** [Helias/Keira2#27]
Make for 2.4.3  ( TBC )  the item  and creature 
thanks  :+1:

**Comment by ShinDarth** [comment]
I'm sorry but we don't have enough developers to support also 2.4.3 :(

**Comment by cyberpro98** [comment]
Well it's not hard :+1:

**Comment by ShinDarth** [comment]
@cyberpro98  we accept PRs, you are free to help us and implement the 2.4.3 :)   (or any other feature/improvement)

**Comment by cyberpro98** [comment]
Ye, sure but i don't know  a lot of PhP 
How can i contact you ?

**Comment by ShinDarth** [comment]
You can contact me using [Telegram](https://telegram.org/), my username is @ShinDarth
