### ISSUE TITLE
SAI editor table for ultrawide screens

### ISSUE THREAD

**Issue by ShinDarth** [Helias/Keira2#3]
Need to adapt the SAI editor table for ultrawide screens.

http://i.gyazo.com/02ff68f56aaf79bbaa48535aa960776f.png

**Comment by Discover-** [comment]
Isn't this more of a general issue rather than just the SAI-Editor? Looks like the entire thing has a fixed width.

**Comment by ShinDarth** [comment]
yes but it seems the other parts don't need more space, while the SAI Editor having "Display basic informations" option disabled, really does

**Comment by Discover-** [comment]
Ah, alright.
