### ISSUE TITLE
trainer_class

### ISSUE THREAD

**Issue by MitikoTsuboi** [Helias/Keira2#30]
For 3.3.5
The right is as follows:
/* creature classes constants */
  app.modalConstants.classes = [];
  app.modalConstants.classes[1]  = "WARRIOR";
  app.modalConstants.classes[2]  = "PALADIN";
  app.modalConstants.classes[3]  = "HUNTER";
  app.modalConstants.classes[4]  = "ROGUE";
  app.modalConstants.classes[5]  = "PRIEST";
  app.modalConstants.classes[6]  = "DEATH_KNIGHT ";
  app.modalConstants.classes[7]  = "SHAMAN";
  app.modalConstants.classes[8]  = "MAGE";
  app.modalConstants.classes[9]  = "WARLOCK";
  app.modalConstants.classes[10]  = "UNK";
  app.modalConstants.classes[11] = "DRUID";

But yours is like this:
/* creature classes constants */
  app.modalConstants.classes = [];
  app.modalConstants.classes[0]  = "WARRIOR";
  app.modalConstants.classes[1]  = "PALADIN";
  app.modalConstants.classes[2]  = "HUNTER";
  app.modalConstants.classes[3]  = "ROGUE";
  app.modalConstants.classes[4]  = "PRIEST";
  app.modalConstants.classes[5]  = "DEATH_KNIGHT ";
  app.modalConstants.classes[6]  = "SHAMAN";
  app.modalConstants.classes[7]  = "MAGE";
  app.modalConstants.classes[8]  = "WARLOCK";
  app.modalConstants.classes[9]  = "UNK";
  app.modalConstants.classes[10] = "DRUID";

The file name is: constants.js
Thanks!

**Comment by Helias** [comment]
Thanks a lot! I fixed also the trainer_race which have the some problems about the constant values.
Anyway the problem weren't the indexes of the array but the values, that constants.classes are used in multiple field so I decided to not modify that but the structure of the "openValueModal" adding a modifier variable to fix some errors like this.

Anyway, thanks!
