### ISSUE TITLE
Comment generation

### ISSUE THREAD

**Issue by KnYaZuK** [Helias/Keira2#31]
If in SAI editor phase set to 1-9, then comment generation isn`t work

**Comment by Helias** [comment]
So if you set the phase (values between 1-9) the button "Generate comment" doesn't work?

Are you sure? It seems to work here http://shinworld.altervista.org/Keira2/#/sai/0/123

**Comment by KnYaZuK** [comment]
Try here http://shinworld.altervista.org/Keira2/#/sai/0/17892

**Comment by Helias** [comment]
It works for me :/, what do you expect in the comment? I get "Infinite Chronomancer - Out of Combat - Disable Combat Movement (Phases 1 & 2 & 4) (No Repeat) (Dungeon)"

and as you can see there are the phases.

![ss](https://cloud.githubusercontent.com/assets/519778/18513035/03d09b7e-7a8c-11e6-93f8-85fe1034d6d6.png)


Try to delete cache, or use another browser

**Comment by KnYaZuK** [comment]
yeah, it`s work on firefox. Thx =)

**Comment by Helias** [comment]
You was right, Chrome doesn't support Array.reverse(array), I changed it in array.reverse() that is the standard function to reverse an array, thx for report.
