### ISSUE TITLE
quest_offer_reward is not defined

### ISSUE THREAD

**Issue by peycho** [Helias/Keira2#33]
When I set some text in OfferRewardText filed, update button does not detect change and full sql does not detect the ID in quest_offer_reward.

![screenshot from 2016-12-04 19 23 40](https://cloud.githubusercontent.com/assets/170853/20867894/39e1a180-ba57-11e6-8a43-7bfad241434c.png)

**Comment by ShinDarth** [comment]
when was this table removed on tc ?

**Comment by tkrokli** [comment]
If you are talking about the 3.3.5 branch, it has not been removed. It may have changed layout, though.
If you are talking about the master branch (7.x), I'm not sure, but DBC/DB2 is handled quite differently.

**Comment by peycho** [comment]
I'm using 3.3.5 branch for my server.

**Comment by ShinDarth** [comment]
are you using 6.x or 3.3.5 keira2?

**Comment by tkrokli** [comment]
@peycho : is this your own build of Keira2 or the test version http://keira2.altervista.org/Keira2-dev/ ?

**Comment by GnaXi** [comment]
First off, it would be great to know if the issue could be reproduced in another environment than your own, to determine if it is a local configuration issue.

Try it here:
https://gnaxi.net/wow/keira2/

**Comment by Helias** [comment]
I verified that this bug doesn't exist in Keira2 with the last release TDB 335.62
