### ISSUE TITLE
Directly query the DB

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Helias/Keira2#37]
It would be nice to directly query the DB using a button.
For now you have to copy paste the code.
In the Update Script tab and Full Script modal we should implement a button that makes an Ajax call to query the DB.

**Comment by ShinDarth** [comment]
Feel free to open a PR :)


PS: ancora questa me la devi spiegare pero'

Luigi Elle Balotta: <<Shin, lo sai anche tu che alcuni fix ve li tenete privati, non per fare la spia o cosa, ma mi ricordo benissimo che si diceva che alcuni fix non andavano pubblicati, se non sbaglio quelli del progetto (progetto visual studio intendo) azth.. le bugie non le sopporto, ed è uno dei motivi che mi ha spinto a non collaborare più e a continuare da solo..
Dev Chester>>

**Comment by LuigiElleBalotta** [comment]
Mi ricordo di una discussione durante una call su hangout credo in cui non ricordo più i nomi, diceva che alcuni custom fix andavano tenuti privati. 
E anche il mio plugin di Wordpress comunque in giro non l'ho visto, si era parlato di un cms wordpress per trinitycore e non ho visto nemmeno quello
